/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DigitalDeed {
        /**
          * The first name
         */
        "deedText": string;
    }
}
declare global {
    interface HTMLDigitalDeedElement extends Components.DigitalDeed, HTMLStencilElement {
    }
    var HTMLDigitalDeedElement: {
        prototype: HTMLDigitalDeedElement;
        new (): HTMLDigitalDeedElement;
    };
    interface HTMLElementTagNameMap {
        "digital-deed": HTMLDigitalDeedElement;
    }
}
declare namespace LocalJSX {
    interface DigitalDeed {
        /**
          * The first name
         */
        "deedText"?: string;
    }
    interface IntrinsicElements {
        "digital-deed": DigitalDeed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "digital-deed": LocalJSX.DigitalDeed & JSXBase.HTMLAttributes<HTMLDigitalDeedElement>;
        }
    }
}
